import { FeatureInfo } from '../types/features'

export const FEATURES: FeatureInfo[] = [
  // Authentication
  {
    id: 'fingerprint',
    name: 'Fingerprint Authentication',
    category: 'authentication',
    description: 'Authenticate users using fingerprint biometrics',
    supportStatus: 'stable',
    platformSupport: { ios: false, android: true, web: false },
    expoGo: true,
    devBuild: true,
    easBuild: true,
    nativePrebuildRequired: false,
  },
  {
    id: 'face-id',
    name: 'Face ID Authentication',
    category: 'authentication',
    description: 'Authenticate users using Face ID on iOS',
    supportStatus: 'stable',
    platformSupport: { ios: true, android: false, web: false },
    expoGo: true,
    devBuild: true,
    easBuild: true,
    nativePrebuildRequired: false,
  },
  {
    id: 'device-credential',
    name: 'Device Credential Authentication',
    category: 'authentication',
    description: 'Authenticate using device passcode / PIN / pattern',
    supportStatus: 'stable',
    platformSupport: { ios: true, android: true, web: false },
    expoGo: true,
    devBuild: true,
    easBuild: true,
    nativePrebuildRequired: false,
  },
  {
    id: 'secure-storage',
    name: 'Secure Storage',
    category: 'authentication',
    description: 'Store sensitive data using platform keychain / keystore',
    supportStatus: 'stable',
    platformSupport: { ios: true, android: true, web: false },
    expoGo: true,
    devBuild: true,
    easBuild: true,
    nativePrebuildRequired: false,
  },

  // Screen Security
  {
    id: 'screenshot-detect',
    name: 'Screenshot Detection',
    category: 'screen-security',
    description: 'Detect when user takes a screenshot',
    supportStatus: 'stable',
    platformSupport: { ios: true, android: true, web: false },
    expoGo: false,
    devBuild: true,
    easBuild: true,
    nativePrebuildRequired: true,
  },
  {
    id: 'screenshot-prevent',
    name: 'Screenshot Prevention',
    category: 'screen-security',
    description: 'Prevent screenshots of sensitive screens',
    supportStatus: 'stable',
    platformSupport: { ios: true, android: true, web: false },
    expoGo: false,
    devBuild: true,
    easBuild: true,
    nativePrebuildRequired: true,
  },
  {
    id: 'recording-detect',
    name: 'Screen Recording Detection',
    category: 'screen-security',
    description: 'Detect when screen is being recorded',
    supportStatus: 'stable',
    platformSupport: { ios: true, android: false, web: false },
    expoGo: false,
    devBuild: true,
    easBuild: true,
    nativePrebuildRequired: true,
  },
  {
    id: 'recording-prevent',
    name: 'Screen Recording Prevention',
    category: 'screen-security',
    description: 'Prevent screen recording of sensitive content',
    supportStatus: 'beta',
    platformSupport: { ios: true, android: true, web: false },
    expoGo: false,
    devBuild: true,
    easBuild: true,
    nativePrebuildRequired: true,
  },
  {
    id: 'casting-detect',
    name: 'Screen Casting Detection',
    category: 'screen-security',
    description: 'Detect when screen is being cast / mirrored',
    supportStatus: 'beta',
    platformSupport: { ios: true, android: true, web: false },
    expoGo: false,
    devBuild: true,
    easBuild: true,
    nativePrebuildRequired: true,
  },

  // Device Security
  {
    id: 'root-detect',
    name: 'Root Detection',
    category: 'device-security',
    description: 'Detect rooted Android devices',
    supportStatus: 'beta',
    platformSupport: { ios: false, android: true, web: false },
    expoGo: false,
    devBuild: true,
    easBuild: true,
    nativePrebuildRequired: true,
  },
  {
    id: 'jailbreak-detect',
    name: 'Jailbreak Detection',
    category: 'device-security',
    description: 'Detect jailbroken iOS devices',
    supportStatus: 'beta',
    platformSupport: { ios: true, android: false, web: false },
    expoGo: false,
    devBuild: true,
    easBuild: true,
    nativePrebuildRequired: true,
  },
  {
    id: 'emulator-detect',
    name: 'Emulator Detection',
    category: 'device-security',
    description: 'Detect if running on emulator / simulator',
    supportStatus: 'stable',
    platformSupport: { ios: true, android: true, web: false },
    expoGo: true,
    devBuild: true,
    easBuild: true,
    nativePrebuildRequired: false,
  },
  {
    id: 'dev-mode-detect',
    name: 'Developer Mode Detection',
    category: 'device-security',
    description: 'Detect if developer mode is enabled',
    supportStatus: 'beta',
    platformSupport: { ios: false, android: true, web: false },
    expoGo: false,
    devBuild: true,
    easBuild: true,
    nativePrebuildRequired: true,
  },
  {
    id: 'mock-location-detect',
    name: 'Mock Location Detection',
    category: 'device-security',
    description: 'Detect if mock location provider is active',
    supportStatus: 'beta',
    platformSupport: { ios: false, android: true, web: false },
    expoGo: false,
    devBuild: true,
    easBuild: true,
    nativePrebuildRequired: true,
  },

  // Device Monitoring
  {
    id: 'network-detect',
    name: 'Network Detection',
    category: 'device-monitoring',
    description: 'Monitor network connectivity state',
    supportStatus: 'stable',
    platformSupport: { ios: true, android: true, web: true },
    expoGo: true,
    devBuild: true,
    easBuild: true,
    nativePrebuildRequired: false,
  },
  {
    id: 'battery-detect',
    name: 'Battery Detection',
    category: 'device-monitoring',
    description: 'Monitor battery level and charging state',
    supportStatus: 'stable',
    platformSupport: { ios: true, android: true, web: false },
    expoGo: true,
    devBuild: true,
    easBuild: true,
    nativePrebuildRequired: false,
  },
  {
    id: 'location-detect',
    name: 'Location Detection',
    category: 'device-monitoring',
    description: 'Monitor device location and permissions',
    supportStatus: 'stable',
    platformSupport: { ios: true, android: true, web: true },
    expoGo: true,
    devBuild: true,
    easBuild: true,
    nativePrebuildRequired: false,
  },
  {
    id: 'shake-detect',
    name: 'Shake Detection',
    category: 'device-monitoring',
    description: 'Detect device shake gestures',
    supportStatus: 'stable',
    platformSupport: { ios: true, android: true, web: false },
    expoGo: true,
    devBuild: true,
    easBuild: true,
    nativePrebuildRequired: false,
  },
  {
    id: 'app-state',
    name: 'App State Monitoring',
    category: 'device-monitoring',
    description: 'Monitor app foreground / background state',
    supportStatus: 'stable',
    platformSupport: { ios: true, android: true, web: true },
    expoGo: true,
    devBuild: true,
    easBuild: true,
    nativePrebuildRequired: false,
  },

  // Enterprise
  {
    id: 'push-notifications',
    name: 'Push Notifications',
    category: 'enterprise',
    description: 'Send and receive push notifications',
    supportStatus: 'stable',
    platformSupport: { ios: true, android: true, web: false },
    expoGo: true,
    devBuild: true,
    easBuild: true,
    nativePrebuildRequired: false,
  },
  {
    id: 'deep-linking',
    name: 'Deep Linking',
    category: 'enterprise',
    description: 'Handle deep links into the app',
    supportStatus: 'stable',
    platformSupport: { ios: true, android: true, web: true },
    expoGo: true,
    devBuild: true,
    easBuild: true,
    nativePrebuildRequired: false,
  },
  {
    id: 'qr-scanner',
    name: 'QR Scanner',
    category: 'enterprise',
    description: 'Scan QR codes using the camera',
    supportStatus: 'stable',
    platformSupport: { ios: true, android: true, web: true },
    expoGo: true,
    devBuild: true,
    easBuild: true,
    nativePrebuildRequired: false,
  },
  {
    id: 'nfc',
    name: 'NFC',
    category: 'enterprise',
    description: 'Read and write NFC tags',
    supportStatus: 'beta',
    platformSupport: { ios: true, android: true, web: false },
    expoGo: false,
    devBuild: true,
    easBuild: true,
    nativePrebuildRequired: true,
  },
  {
    id: 'analytics',
    name: 'Analytics',
    category: 'enterprise',
    description: 'Track user events and app usage',
    supportStatus: 'stable',
    platformSupport: { ios: true, android: true, web: true },
    expoGo: true,
    devBuild: true,
    easBuild: true,
    nativePrebuildRequired: false,
  },
  {
    id: 'crash-reporting',
    name: 'Crash Reporting',
    category: 'enterprise',
    description: 'Capture and report app crashes',
    supportStatus: 'stable',
    platformSupport: { ios: true, android: true, web: true },
    expoGo: true,
    devBuild: true,
    easBuild: true,
    nativePrebuildRequired: false,
  },

  // Security
  {
    id: 'ssl-pinning',
    name: 'SSL Pinning',
    category: 'security',
    description: 'Pin SSL certificates for secure network communication',
    supportStatus: 'beta',
    platformSupport: { ios: true, android: true, web: false },
    expoGo: false,
    devBuild: true,
    easBuild: true,
    nativePrebuildRequired: true,
  },
  {
    id: 'session-management',
    name: 'Session Management',
    category: 'security',
    description: 'Manage user sessions with tokens and refresh',
    supportStatus: 'stable',
    platformSupport: { ios: true, android: true, web: true },
    expoGo: true,
    devBuild: true,
    easBuild: true,
    nativePrebuildRequired: false,
  },
  {
    id: 'auto-logout',
    name: 'Auto Logout',
    category: 'security',
    description: 'Automatically log out inactive users',
    supportStatus: 'stable',
    platformSupport: { ios: true, android: true, web: true },
    expoGo: true,
    devBuild: true,
    easBuild: true,
    nativePrebuildRequired: false,
  },
  {
    id: 'device-binding',
    name: 'Device Binding',
    category: 'security',
    description: 'Bind sessions to specific devices',
    supportStatus: 'beta',
    platformSupport: { ios: true, android: true, web: false },
    expoGo: false,
    devBuild: true,
    easBuild: true,
    nativePrebuildRequired: true,
  },
  {
    id: 'force-update',
    name: 'Force Update',
    category: 'security',
    description: 'Force users to update the app',
    supportStatus: 'stable',
    platformSupport: { ios: true, android: true, web: true },
    expoGo: true,
    devBuild: true,
    easBuild: true,
    nativePrebuildRequired: false,
  },
]

export const FEATURE_CATEGORIES = [
  { id: 'authentication' as const, label: 'Authentication', icon: 'lock' },
  { id: 'screen-security' as const, label: 'Screen Security', icon: 'monitor' },
  { id: 'device-security' as const, label: 'Device Security', icon: 'shield' },
  { id: 'device-monitoring' as const, label: 'Device Monitoring', icon: 'activity' },
  { id: 'enterprise' as const, label: 'Enterprise', icon: 'briefcase' },
  { id: 'security' as const, label: 'Security', icon: 'shield-alert' },
]
